//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advisor
    {
        public Advisor()
        {
            this.Appointments = new HashSet<Appointment>();
            this.CareerFairs = new HashSet<CareerFair>();
            this.CareerPlans = new HashSet<CareerPlan>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Jobs = new HashSet<Job>();
        }
    
        public long AdvisorID { get; set; }
        public string AdvisorFirstName { get; set; }
        public string AdvisorLastName { get; set; }
        public string AdvisorTitle { get; set; }
        public string AdvisorLocation { get; set; }
        public string AdvisorEmail { get; set; }
        public string AdvisorAddress { get; set; }
        public string AdvisorCity { get; set; }
        public string AdvisorState { get; set; }
        public string AdvisorZip { get; set; }
        public string AdvisorOfficePhone { get; set; }
        public string AdvisorMobilePhone { get; set; }
        public string AdvisorLevel { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<CareerFair> CareerFairs { get; set; }
        public virtual ICollection<CareerPlan> CareerPlans { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
