//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentID { get; set; }
        public long StudentID { get; set; }
        public long AdvisorID { get; set; }
        public System.DateTime ApointmentDate { get; set; }
        public System.TimeSpan ApointmentTime { get; set; }
        public string AppointmentType { get; set; }
        public string AppointmentLocation { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Student Student { get; set; }
    }
}
