//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerFair
    {
        public long CareerFairID { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string LocationName { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Sponsor { get; set; }
        public long AdvisorID { get; set; }
        public long RecruiterID { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Recruiter Recruiter { get; set; }
    }
}
