//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerPlan
    {
        public long CareerPlanID { get; set; }
        public long StudentID { get; set; }
        public long AdvisorID { get; set; }
        public long RecruiterID { get; set; }
        public byte[] Resume { get; set; }
        public string AdvisorCareerForecast { get; set; }
        public string RecruiterCareerForecast { get; set; }
        public string StudentCareerGoals { get; set; }
        public string JobLocationState { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Student Student { get; set; }
    }
}
