//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public long EnrollmentID { get; set; }
        public long StudentID { get; set; }
        public long SectionID { get; set; }
        public string Grade { get; set; }
        public Nullable<decimal> GradePoint { get; set; }
        public Nullable<decimal> Credits { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Student Student { get; set; }
    }
}
