//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long FeedbackID { get; set; }
        public string FeedbackType { get; set; }
        public long StudentID { get; set; }
        public long AdvisorID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Advisor Advisor { get; set; }
        public virtual Student Student { get; set; }
    }
}
