//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Instructors = new HashSet<Instructor>();
            this.Sections = new HashSet<Section>();
        }
    
        public long RoomID { get; set; }
        public string Description { get; set; }
        public Nullable<short> Capacity { get; set; }
        public Nullable<bool> Lab { get; set; }
        public string LabType { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BuidingID { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
