//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Appointments = new HashSet<Appointment>();
            this.CareerPlans = new HashSet<CareerPlan>();
            this.Enrollments = new HashSet<Enrollment>();
            this.Feedbacks = new HashSet<Feedback>();
            this.StudentAddresses = new HashSet<StudentAddress>();
            this.StudentAvailabilities = new HashSet<StudentAvailability>();
        }
    
        public long StudentID { get; set; }
        public string FirstName { get; set; }
        public string MI { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public System.DateTime DOB { get; set; }
        public string Email { get; set; }
        public Nullable<long> MajorID { get; set; }
        public Nullable<long> MinorID { get; set; }
        public string Phone { get; set; }
        public string EnrollmentStatus { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<CareerPlan> CareerPlans { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Program Program { get; set; }
        public virtual Program Program1 { get; set; }
        public virtual ICollection<StudentAddress> StudentAddresses { get; set; }
        public virtual ICollection<StudentAvailability> StudentAvailabilities { get; set; }
    }
}
